In [ ]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [ ]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1] # 0부터 맨뒤 끊어진거 끊어와라->X
  print("X=",input_features) # 행 형태 1행4열
  
  labels = np.reshape(data[:,-1],(4,1)) # 4행1열로 바꿈
  print("Y=",labels)
 
  input_features = torch.tensor(input_features, dtype=torch.float)
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/My Drive/colab/ann/xor1/train.txt") # 무조건 해야함

# layer 1 가중치 초기화
# 이곳을 완성하세요.
w1 = torch.randn(2,2,requires_grad=True) # torch.randn : 정규분포 해라
b1 = torch.randn(2,requires_grad=True)
print("\n[Init]\nw1 = {0}".format(tensor2list(w1))) # tensor2list -> tensor는 객체라 텐서형으로 나옴 그래서 리스트로 바꿔서 찍음
print("b1 = {0}".format(tensor2list(b1)))

# layer 2 가중치 초기화
# 이곳을 완성하세요.
w2 = torch.randn(2,1,requires_grad=True) # torch.randn : 정규분포 해라
b2 = torch.randn(1,requires_grad=True)

# 날코딩으로 하면 H(x) 언더플로우 생김

print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# Activation 함수 설정
sigmoid = nn.Sigmoid() # pytorch nn에 sigmoid 쓰겠다. 언더플로우 막으려고 조그만 수 더해줌

# 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss() # 바이너리 크로스엔트로피 

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1,b1,w2,b2],lr=0.2) # SGD 경사하강법??, 업데이트할것들을 리스트 형태로 넣어줌, learningrate=0.2

# 모델 학습
for epoch in range(1001):

    # H(X) 계산: forward 연산
    # 이곳을 완성하세요.
    #matmul->matrixmultiply
    L2=sigmoid(torch.add(torch.matmul(x,w1),b1)) # x*w1+b1하고 sigmoid 여기서 아웃풋값 꺼냄
    hx=sigmoid(torch.add(torch.matmul(L2,w2),b2)) # L2*w2+b2 하고 sigmoid
    # 비용 계산
    cost = loss_func(hx, y) # bce 아까 정의

    #### backpropagation -> gradient update ####
    # 두줄의 코드가 backpropagation
    # 역전파 수행
    cost.backward() # backward 방향으로 가중치 업데이트
    # cost를 역방향으로 보냄
    optimizer.step() # 옵티마이저 실행

    # 100 에폭마다 비용 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# 모델 평가
# H(X) 계산: forward 연산
# 이곳을 완성사에요.
# H(x)이 0.5보다 크면 true
# sigmoid 했으므로 0~1 사이 값 나옴

L2=sigmoid(torch.add(torch.matmul(x,w1),b1)) # x*w1+b1하고 sigmoid 여기서 아웃풋값 꺼냄
hx=sigmoid(torch.add(torch.matmul(L2,w2),b2)) # L2*w2+b2 하고 sigmoid

logits = (hx > 0.5).float() # logits란??
predicts = tensor2list(logits)
golds = tensor2list(y)

print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))



DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[-1.1862314939498901, 0.3101063072681427], [-0.8083272576332092, 0.014147043228149414]]
b1 = [0.2902979254722595, 0.6158347129821777]
w2 = [[-1.180893063545227], [0.08467705547809601]]
b2 = [-0.1970536708831787]

0 0.7249121069908142
100 0.4316980540752411
200 6.347926046146313e-06
300 0.0
400 0.0
500 0.0
600 0.0
700 0.0
800 0.0
900 0.0
1000 0.0

[Learned]
w1 = [[-158.5913543701172, -104.3956527709961], [-150.0393524169922, -107.41055297851562]]
b1 = [43.17057418823242, 203.42250061035156]
w2 = [[-171.21363830566406], [274.86651611328125]]
b2 = [-167.51661682128906]


PRED= [[0.0], [1.0], [1.0], [0.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 1.000000
